from sentinel.version_manifest import (
    SENTINEL_VERSION, SENTINEL_BUILD, SENTINEL_CONSTITUTION, AGENT_SIGNATURE
)

SYSTEM_VERSION    = SENTINEL_VERSION
SYSTEM_CODENAME   = f"{SENTINEL_BUILD}_{SENTINEL_CONSTITUTION}"

TRADE_COMMENT_TEMPLATE = f"{AGENT_SIGNATURE}_{{symbol}}_{{regime}}_{{signal_type}}"
